services:
  - type: web
    name: Fitness Equation
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: "DATABASE_URL"  # This is the correct key
        value: "postgresql://brian:199613@localhost:5432/db"  # Replace with your actual Render DB connection string
      - key: "SECRET_KEY_BASE"
        generateValue: true
      - key: "WEB_CONCURRENCY"
        value: 2

databases:
  - name: db
    plan: free
    ipAllowList: []
