services:
  - type: web
    name: Fitness Equation # the name of this service, you should change this if needed
    runtime: ruby # this app is written in ruby
    plan: free # make sure to set this to free or you'll get billed $$$
    buildCommand: "./bin/render-build.sh" # we already created these two files for you
    startCommand: "./bin/render-start.sh"
    envVars: # this section sets some ENV variables needed by Render for deployment
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: db # Ensure this matches the name in the "databases" section below
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 2

databases: # this section provides some additional database configuration
  - name: db # Make sure this name matches the one used in the envVars section
    plan: free
    ipAllowList: []
