services:
  - type: web
    name: Fitness Equation
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://db_3dt2_user:your_password@dpg-cujspb5ds7s739j3md0-a:5432/db_3dt2
      - key: WEB_CONCURRENCY
        value: 2

databases:
  - name: db
    plan: free
    ipAllowList: []
