services:
  - type: web
    name: Fitness Equation
    runtime: ruby
    plan: free
    buildCommand: ./bin/render-build.sh
    startCommand: ./bin/render-start.sh
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        value: "postgresql://db_zel3_user:mjhNqbHjVZ5pgfeEBsfXT7IDO7v6xh02@dpg-cuk0fcrtq21c73e2p0j0-a.oregon-postgres.render.com/db_zel3"
      - key: WEB_CONCURRENCY
        value: 2
