default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['FITNESS_EQUATION_DATABASE_USERNAME'] %>
  password: <%= ENV['FITNESS_EQUATION_DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: brian
  username: brian
  password: 199613
  host: localhost

test:
  <<: *default
  database: brian
  username: brian
  password: 199613
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
