services:
  - type: web
    name: Fitness Equation
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        value: "postgres://user:password@localhost:5432/fitness_equation"  # Replace with your actual connection string
      - key: WEB_CONCURRENCY
        value: 2

databases:
  - name: fitness_equation
    plan: free
    ipAllowList: []
