default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['FITNESS_EQUATION_DATABASE_USERNAME'] %>
  password: <%= ENV['FITNESS_EQUATION_DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

test:
  <<: *default
  database: fitness_equation_test

development:
  <<: *default
  database: fitness_equation_development
  username: <%= ENV['FITNESS_EQUATION_DATABASE_USERNAME'] %>
  password: <%= ENV['FITNESS_EQUATION_DATABASE_PASSWORD'] %>
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>  # Ensure the DATABASE_URL for production points to the remote database
