default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: brian
  password: 199613
  host: localhost

development:
  <<: *default
  database: fitness_equation_development

test:
  <<: *default
  database: fitness_equation_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: fitness_equations_production
  username: <%= ENV["FITNESS_EQUATION_DATABASE_USERNAME"] %>
  password: <%= ENV["FITNESS_EQUATION_DATABASE_PASSWORD"] %>
  host: 35.227.164.209
  port: 5432
  sslmode: require
