default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: postgresql://db_3dt2_user:your_password@dpg-cujspb5ds7s739j3md0-a:5432/db_3dt2

test:
  <<: *default
  database: fitness_equation_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
