default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db_3dt2
  username: db_3dt2_user
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: dpg-cujspb5ds7s739j3md0-a
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
