default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['FITNESS_EQUATION_DATABASE_USERNAME'] %>
  password: <%= ENV['FITNESS_EQUATION_DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: fitness_equation_development

test:
  <<: *default
  database: fitness_equation_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: fitness_equations_production
  username: <%= ENV["FITNESS_EQUATION_DATABASE_USERNAME"] %>
  password: <%= ENV["FITNESS_EQUATION_DATABASE_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL_PRODUCTION'] %>
  port: 5432
  sslmode: require
