default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>  # Automatically uses Render's DATABASE_URL

development:
  <<: *default
  database: fitness_equation_development

test:
  <<: *default
  database: fitness_equation_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
