default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['FITNESS_EQUATION_DATABASE_USERNAME'] %>
  password: <%= ENV['FITNESS_EQUATION_DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: brian
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>

test:
  <<: *default
  database: brian
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV["FITNESS_EQUATION_DATABASE_USERNAME"] %>
  password: <%= ENV["FITNESS_EQUATION_DATABASE_PASSWORD"] %>
