default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['FITNESS_EQUATION_DATABASE_USERNAME'] %>
  password: <%= ENV['FITNESS_EQUATION_DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: brian

test:
  <<: *default
  database: brian

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>  # This will now be set from Render's DATABASE_URL
