default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: fitness_equation_development

test:
  <<: *default
  database: fitness_equation_test

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
  timeout: 5000
